function [resampledVolume,...
          resampledAtlas, ...  
          resampledBodyMask] = volumeResampling(volume,atlas,bodyMask,...
                                                  scaleInfo, atlasInfo)
% In this function all the volumes needed for the atlas segmentation are
% resampled in order for them to have isotopic voxels.  
% 
% Input: - volume:            CT volume data
%
%        - atlas:             Atlas volume data 
%
%        - bodyMask:          Binary mask containing the body of the
%                             patient
%
%        - scaleInfo:         Vector containing the voxel size of the CT 
%                             volume, [sx, sy, sz].
%
%        - atlasInfo:         Vector containing the voxel size of the Atlas
%                             [atlas_sx, atlas_sy, atlas_sy].
%
%   [resampledVolume,...
%    resampledAtlas, ...
%    resampledBoneAtlas] = resampling(volume,atlas, bodyMask,...
%                                     scaleInfo, atlasInfo)

% Atlas
[resampledAtlas,~] = getIsotropicVoxels(atlas,atlasInfo(1), ...
                                              atlasInfo(2), ...
                                              atlasInfo(3), ...
                                              'nearest');

% Volume
[resampledVolume,~] = getIsotropicVoxels(volume,scaleInfo(1), ...
                                                scaleInfo(2), ...
                                                scaleInfo(3), ...
                                                'linear');
                                    
% Body mask
[resampledBodyMask,~] = getIsotropicVoxels(bodyMask,scaleInfo(1), ...
                                                    scaleInfo(2), ...
                                                    scaleInfo(3), ...
                                                    'nearest');
% Ensures that the mask is binary.
resampledBodyMask = resampledBodyMask > 0.5;     


end